name: Lint, Scan and build 

on: push

jobs:
  semgrep:
      name: Scan
      runs-on: ubuntu-latest
      # Skip any PR created by dependabot to avoid permissioning issues
      if: (github.actor != 'dependabot[bot]')
      steps:
        # Checkout project source
        - uses: actions/checkout@v2

        # Scan code using project's configuration on https://semgrep.dev/manage
        - uses: returntocorp/semgrep-action@v1

          # Optionally configure job timeout (default is 1800 seconds; set to 0 to disable)
          #env:
          #  SEMGREP_TIMEOUT: 300
          with:
            # Never fail the build due to findings on pushes, but collect findings data
            auditOn: push

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
    - uses: actions/cache@v1    
    - name: Lint
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
      run: |
        npm install
        npm run-script lint
    - name: Build
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
      run: |
        npm install
        npm run-script build