name: Lint, Scan and build 

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
    - uses: actions/cache@v1    
    - name: Lint
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
      run: |
        npm install
        npm run-script lint
    - name: Build
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
      run: |
        npm install
        npm run-script build

  semgrep:
      name: Scan
      image: returntocorp/semgrep-agent:v1
      runs-on: ubuntu-latest
      script: semgrep-agent
      variables:
        SEMGREP_RULES: >- # more at semgrep.dev/explore
          p/security-audit
          p/secrets